### ISSUE TITLE
Error parsing triggers: Cannot find module 'modelo'

### ISSUE THREAD

**Issue by Nakul97** [firebase/functions-samples#249]
I am getting a very weird issue while trying to run the sample for stripe-firebase 

I have spent hours searching for this but I cant find that I have used 'modelo' module anywhere. I am really stuck. 

I simply used the index.js , package.json file that was used in the example, recreated my directory but the same error again.

**Comment by Nakul97** [comment]
Seams it was a problem with my npm installation.

**Comment by Seikilos** [comment]
Would be great if you could explain what actually was wrong because I have the same issue here.

**Comment by vivekmago** [comment]
same issue here as well.. just started happening...

**Comment by jamiehumphries** [comment]
I just started experiencing this issue about an hour or two ago, having been deploying functions successfully earlier in the day.

**Comment by Seikilos** [comment]
The fun part for me is: I am trying to get the local emulator working, which fails with this. Did not test deploying today.

**Comment by Seikilos** [comment]
Does somebody know whether it is possible to actually pin modelo to 4.2.0 for `npm install -g firebase-tools` ? Install modelo 4.2.0 globally? Revert to previous tools?

**Comment by kevinconway** [comment]
I pushed up 4.2.2 which reverts the NPM config change and fits within the semver pinning that most projects are using to pull in `modelo`. See if that has provided any relieve.

If you can provide me with any of the error output I'd appreciate it. I'm looking into reproducing and fixing this issue.

**Comment by dcfax** [comment]
just have this issue since 2 hours, anybody found the turnaroud ?


Code in file index.js can't be loaded. Did you list all required modules in the package.json dependencies? Detailed stack trace: Error: Cannot find module 'modelo'     at Function.Module._resolveFilename (module.js:469:15)     at Function.Module._load (module.js:417:25)     at Module.require (module.js:497:17)     at require (internal/module.js:20:19)     at Object.<anonymous> (/user_code/node_modules/@google-cloud/storage/node_modules/@google-cloud/common/src/operation.js:25:14)     at Module._compile (module.js:570:32)     at Object.Module._extensions..js (module.js:579:10)     at Module.load (module.js:487:32)     at tryModuleLoad (module.js:446:12)     at Function.Module._load (module.js:438:3)
--

**Comment by Seikilos** [comment]
@kevinconway I reinstalled `npm install -g firebase-tools` and ensured modelo is up to 4.2.2 which it is, but calling `firebase experimental:functions:shell` still causes 
`!  functions: Cannot start emulator. Error: Cannot find module 'modelo'`

There is nothing more, when I run firebase --debug I get some private firebase urls to my projects but nothing there to troubleshoot.

Here is the header

```
> firebase --debug experimental:functions:shell
[2018-01-06T17:57:17.412Z] ----------------------------------------------------------------------
[2018-01-06T17:57:17.415Z] Command:       c:\program files\nodejs\node.exe C:\Users\<User>\AppData\Roaming\npm\node_modules\firebase-tools\bin\firebase --debug experimental:functions:shell
[2018-01-06T17:57:17.416Z] CLI Version:   3.16.0
[2018-01-06T17:57:17.417Z] Platform:      win32
[2018-01-06T17:57:17.417Z] Node Version:  v7.2.1
[2018-01-06T17:57:17.417Z] Time:          Sat Jan 06 2018 18:57:17 GMT+0100 (Mitteleuropäische Zeit)
[2018-01-06T17:57:17.417Z] ----------------------------------------------------------------------
<some requests to my firebase account>
...
!  functions: Cannot start emulator. Error: Cannot find module 'modelo'
```

**Comment by Nakul97** [comment]
I solved it by deleting installed dependencies and .lock file then running npm install once again.

**Comment by kevinconway** [comment]
I believe the issue is resolved. https://github.com/kevinconway/Modelo.js/pull/24 appears to have been the reason for the missing code files.

**Comment by kevinconway** [comment]
Yeah, I'm guessing the cached `4.2.2` version is still being used as it satisfies the semver range in the config file. Are you able to run `npm cache clean` on the machine you're using for build/deploy?

**Comment by FrangSierra** [comment]
I tried to clean my cache and add a dependency in my `package.json` has @cyberflohr says. And I still getting the error. Someone was able to solve it in other way? I already unninstalled and installed npm dependencies, deleted cache and deleted `lock` file

**Comment by dcfax** [comment]
it was working  again on deploy during a few minutes, but now i have :

Build failed: exit status 1 npm ERR! Linux 4.4.0-103-generic npm ERR! argv "/nodejs/bin/node" "/nodejs/bin/npm" "--global-style" "--production" "--fetch-retries=5" "--fetch-retry-factor=2" "--fetch-retry-mintimeout=1000" "install" "/workspace" npm ERR! node v6.11.5 npm ERR! npm  v3.10.10  npm ERR! Cannot convert undefined or null to object npm ERR!  npm ERR! If you need help, you may report this error at: npm ERR!     <https://github.com/npm/npm/issues>  npm ERR! Please include the following file with any support request: npm ERR!     /workspace/npm-debug.log
--

**Comment by Seikilos** [comment]
@FrangSierra I had some issues later on too. Looks like I had still references to older modelo in other packages. I searched for all package.json (global npm install) and my local package and replaced them by 4.2.3. Then I installed this version locally and globally and everything works now. I suppose that there is still some other package using the old one.
The packages I found beside firebase-tools:

- @google-cloud/common
- @google-cloud/grpc

and their children.

**Comment by FrangSierra** [comment]
Exactly @dcfax , I got that error now after add the modelo dependency

**Comment by meandevstar** [comment]
I have installed modelo package both locally and globally, but still get deployment error

**Comment by kevinconway** [comment]
I can't weight in on the NPM error, but I've removed the invalid `modelo` versions from NPM such that they should no longer be pulled in for `npm install`. Continued errors related to missing `modelo` files will likely be due to some kind of caching or stale data on a machine.

**Comment by fsciam** [comment]
I've resolved simply with ```npm cache clean --force; npm install modelo@4.2.3```

**Comment by razvanbretoiu** [comment]
Hi, when I try to install all the dependencies I get the following error `An unexpected error occurred: "https://registry.yarnpkg.com/modelo/-/modelo-4.2.1.tgz: Request failed \"404 Not Found\"".`. I looked into yarn-debug.log and I saw that `@google-cloud/common-grpc@^0.5.0` and `@google-cloud/common@^0.13.0` use `modelo "^4.2.0"` which is resolved by version 4.2.1: 
`modelo@^4.2.0:version "4.2.1"
resolved "https://registry.yarnpkg.com/modelo/-/modelo-4.2.1.tgz#df2e394210c0e9e6b5bab64d75dd0c9050f26f3a"`

**Comment by CodingDoug** [comment]
There is a problem with the NPM registry.  Lots of people are experiencing difficulty.  Might have to just wait this one out until they fix it.

https://github.com/npm/registry/issues/255

**Comment by kevinconway** [comment]
To be clear, I've removed `modelo@4.2.1` and `modelo@4.2.2` from the NPM registry as they were invalid packages and to prevent future `npm install`s from pulling them in. There is a `modelo@4.2.3` that is valid and published to the registry. If your system is still trying to pull in one of the removed versions then you likely need to clear you local cache and delete the lock file so that it pulls in the correct versions.

That being said, NPM is still having an issue that may cause similar errors as the one you're seeing @razvanbretoiu .
